language:
  - clojure
lein: lein2
jdk:
  - oraclejdk8
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - lein2 clean
  - lein2 cljsbuild clean
  - lein2 cljsbuild once
  - lein2 scss clean
  - lein2 scss once
  - lein2 compile
